const stamfordData = {
    "latitude": 41.04295,
    "longitude": -73.53236,
    "timezone": "America/New_York",
    "hourly": {
        "summary": "Partly cloudy throughout the day.",
        "icon": "partly-cloudy-day",
        "data": [
            {
                "time": 1563249600,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 72.61,
                "apparentTemperature": 72.93,
                "dewPoint": 62.88,
                "humidity": 0.72,
                "pressure": 1017.39,
                "windSpeed": 3.37,
                "windGust": 3.37,
                "windBearing": 65,
                "cloudCover": 0.03,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 315.4
            },
            {
                "time": 1563253200,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 71.86,
                "apparentTemperature": 71.97,
                "dewPoint": 60.98,
                "humidity": 0.69,
                "pressure": 1017.75,
                "windSpeed": 2.69,
                "windGust": 2.69,
                "windBearing": 60,
                "cloudCover": 0.02,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 314.5
            },
            {
                "time": 1563256800,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 69.6,
                "apparentTemperature": 69.91,
                "dewPoint": 62.35,
                "humidity": 0.78,
                "pressure": 1017.7,
                "windSpeed": 2.4,
                "windGust": 2.4,
                "windBearing": 29,
                "cloudCover": 0.02,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 310.7
            },
            {
                "time": 1563260400,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 67.55,
                "apparentTemperature": 67.65,
                "dewPoint": 60.28,
                "humidity": 0.78,
                "pressure": 1017.44,
                "windSpeed": 3.09,
                "windGust": 3.09,
                "windBearing": 353,
                "cloudCover": 0.02,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 310.8
            },
            {
                "time": 1563264000,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 68.1,
                "apparentTemperature": 68.11,
                "dewPoint": 59.67,
                "humidity": 0.74,
                "pressure": 1017.39,
                "windSpeed": 2.08,
                "windGust": 2.08,
                "windBearing": 8,
                "cloudCover": 0.02,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 311.7
            },
            {
                "time": 1563267600,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 66.84,
                "apparentTemperature": 66.91,
                "dewPoint": 59.86,
                "humidity": 0.78,
                "pressure": 1017.59,
                "windSpeed": 2.34,
                "windGust": 2.34,
                "windBearing": 355,
                "cloudCover": 0.02,
                "uvIndex": 0,
                "visibility": 9.957,
                "ozone": 313
            },
            {
                "time": 1563271200,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 66.87,
                "apparentTemperature": 66.91,
                "dewPoint": 59.69,
                "humidity": 0.78,
                "pressure": 1017.82,
                "windSpeed": 2.91,
                "windGust": 2.91,
                "windBearing": 0,
                "cloudCover": 0.02,
                "uvIndex": 0,
                "visibility": 9.863,
                "ozone": 315
            },
            {
                "time": 1563274800,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 68.83,
                "apparentTemperature": 69.07,
                "dewPoint": 61.67,
                "humidity": 0.78,
                "pressure": 1018.18,
                "windSpeed": 2.28,
                "windGust": 2.28,
                "windBearing": 14,
                "cloudCover": 0.06,
                "uvIndex": 0,
                "visibility": 9.654,
                "ozone": 317.3
            },
            {
                "time": 1563278400,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 72.46,
                "apparentTemperature": 72.81,
                "dewPoint": 63.02,
                "humidity": 0.72,
                "pressure": 1018.53,
                "windSpeed": 2.31,
                "windGust": 2.31,
                "windBearing": 73,
                "cloudCover": 0.07,
                "uvIndex": 1,
                "visibility": 9.188,
                "ozone": 320.3
            },
            {
                "time": 1563282000,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 77.14,
                "apparentTemperature": 77.53,
                "dewPoint": 63.66,
                "humidity": 0.63,
                "pressure": 1018.65,
                "windSpeed": 2.33,
                "windGust": 2.33,
                "windBearing": 127,
                "cloudCover": 0.01,
                "uvIndex": 3,
                "visibility": 8.154,
                "ozone": 318.3
            },
            {
                "time": 1563285600,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 77.28,
                "apparentTemperature": 77.51,
                "dewPoint": 62.1,
                "humidity": 0.6,
                "pressure": 1018.48,
                "windSpeed": 4.83,
                "windGust": 4.83,
                "windBearing": 184,
                "cloudCover": 0.01,
                "uvIndex": 5,
                "visibility": 7.449,
                "ozone": 314.6
            },
            {
                "time": 1563289200,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 80.54,
                "apparentTemperature": 81.94,
                "dewPoint": 63.23,
                "humidity": 0.56,
                "pressure": 1018.15,
                "windSpeed": 4.58,
                "windGust": 4.58,
                "windBearing": 193,
                "cloudCover": 0.02,
                "uvIndex": 7,
                "visibility": 8.543,
                "ozone": 311.1
            },
            {
                "time": 1563292800,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 82.63,
                "apparentTemperature": 83.37,
                "dewPoint": 61.8,
                "humidity": 0.49,
                "pressure": 1017.81,
                "windSpeed": 4.54,
                "windGust": 4.54,
                "windBearing": 198,
                "cloudCover": 0.06,
                "uvIndex": 9,
                "visibility": 8.074,
                "ozone": 308.5
            },
            {
                "time": 1563296400,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 83.52,
                "apparentTemperature": 84.24,
                "dewPoint": 62.08,
                "humidity": 0.49,
                "pressure": 1017.31,
                "windSpeed": 5.87,
                "windGust": 5.87,
                "windBearing": 206,
                "cloudCover": 0.08,
                "uvIndex": 9,
                "visibility": 7.428,
                "ozone": 306
            },
            {
                "time": 1563300000,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 86.41,
                "apparentTemperature": 86.73,
                "dewPoint": 61.61,
                "humidity": 0.43,
                "pressure": 1016.79,
                "windSpeed": 7.48,
                "windGust": 7.48,
                "windBearing": 210,
                "cloudCover": 0.11,
                "uvIndex": 9,
                "visibility": 9.526,
                "ozone": 304.2
            },
            {
                "time": 1563303600,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 87.87,
                "apparentTemperature": 88.38,
                "dewPoint": 62.17,
                "humidity": 0.42,
                "pressure": 1016.21,
                "windSpeed": 8.1,
                "windGust": 8.1,
                "windBearing": 214,
                "cloudCover": 0.29,
                "uvIndex": 7,
                "visibility": 10,
                "ozone": 303.4
            },
            {
                "time": 1563307200,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 90.14,
                "apparentTemperature": 91.04,
                "dewPoint": 62.89,
                "humidity": 0.4,
                "pressure": 1015.66,
                "windSpeed": 9.04,
                "windGust": 11.89,
                "windBearing": 221,
                "cloudCover": 0.42,
                "uvIndex": 5,
                "visibility": 10,
                "ozone": 303.4
            },
            {
                "time": 1563310800,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 91.3,
                "apparentTemperature": 92.61,
                "dewPoint": 63.52,
                "humidity": 0.4,
                "pressure": 1015.23,
                "windSpeed": 9.74,
                "windGust": 15.74,
                "windBearing": 219,
                "cloudCover": 0.45,
                "uvIndex": 3,
                "visibility": 10,
                "ozone": 303.2
            },
            {
                "time": 1563314400,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 90.35,
                "apparentTemperature": 92.01,
                "dewPoint": 64.32,
                "humidity": 0.42,
                "pressure": 1015.06,
                "windSpeed": 9.81,
                "windGust": 16.69,
                "windBearing": 211,
                "cloudCover": 0.46,
                "uvIndex": 1,
                "visibility": 10,
                "ozone": 302.4
            },
            {
                "time": 1563318000,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 88.46,
                "apparentTemperature": 90.37,
                "dewPoint": 65.04,
                "humidity": 0.46,
                "pressure": 1015.02,
                "windSpeed": 10.22,
                "windGust": 17.09,
                "windBearing": 199,
                "cloudCover": 0.44,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 301.4
            },
            {
                "time": 1563321600,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 86.52,
                "apparentTemperature": 88.54,
                "dewPoint": 65.43,
                "humidity": 0.5,
                "pressure": 1015.07,
                "windSpeed": 9.97,
                "windGust": 17.23,
                "windBearing": 192,
                "cloudCover": 0.42,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 300.9
            },
            {
                "time": 1563325200,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 84.46,
                "apparentTemperature": 86.93,
                "dewPoint": 66.51,
                "humidity": 0.55,
                "pressure": 1015.28,
                "windSpeed": 9.33,
                "windGust": 16.48,
                "windBearing": 196,
                "cloudCover": 0.44,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 301.3
            },
            {
                "time": 1563328800,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.001,
                "precipProbability": 0.02,
                "precipType": "rain",
                "temperature": 80.54,
                "apparentTemperature": 83.02,
                "dewPoint": 67.32,
                "humidity": 0.64,
                "pressure": 1015.52,
                "windSpeed": 8.41,
                "windGust": 15.68,
                "windBearing": 202,
                "cloudCover": 0.34,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 302.2
            },
            {
                "time": 1563332400,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.002,
                "precipProbability": 0.02,
                "precipType": "rain",
                "temperature": 78.77,
                "apparentTemperature": 79.58,
                "dewPoint": 67.63,
                "humidity": 0.69,
                "pressure": 1015.59,
                "windSpeed": 7.18,
                "windGust": 14.32,
                "windBearing": 209,
                "cloudCover": 0.17,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 302.7
            }
        ]
    },
    "offset": -4
}

const stamfordDataMaybeRain = {
    "latitude": 41.04295,
    "longitude": -73.53236,
    "timezone": "America/New_York",
    "hourly": {
        "summary": "Partly cloudy throughout the day.",
        "icon": "partly-cloudy-day",
        "data": [
            {
                "time": 1563249600,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0.3,
                "temperature": 72.61,
                "apparentTemperature": 72.93,
                "dewPoint": 62.88,
                "humidity": 0.72,
                "pressure": 1017.39,
                "windSpeed": 3.37,
                "windGust": 3.37,
                "windBearing": 65,
                "cloudCover": 0.03,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 315.4
            },
            {
                "time": 1563253200,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 71.86,
                "apparentTemperature": 71.97,
                "dewPoint": 60.98,
                "humidity": 0.69,
                "pressure": 1017.75,
                "windSpeed": 2.69,
                "windGust": 2.69,
                "windBearing": 60,
                "cloudCover": 0.02,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 314.5
            },
            {
                "time": 1563256800,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 69.6,
                "apparentTemperature": 69.91,
                "dewPoint": 62.35,
                "humidity": 0.78,
                "pressure": 1017.7,
                "windSpeed": 2.4,
                "windGust": 2.4,
                "windBearing": 29,
                "cloudCover": 0.02,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 310.7
            },
            {
                "time": 1563260400,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 67.55,
                "apparentTemperature": 67.65,
                "dewPoint": 60.28,
                "humidity": 0.78,
                "pressure": 1017.44,
                "windSpeed": 3.09,
                "windGust": 3.09,
                "windBearing": 353,
                "cloudCover": 0.02,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 310.8
            },
            {
                "time": 1563264000,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 68.1,
                "apparentTemperature": 68.11,
                "dewPoint": 59.67,
                "humidity": 0.74,
                "pressure": 1017.39,
                "windSpeed": 2.08,
                "windGust": 2.08,
                "windBearing": 8,
                "cloudCover": 0.02,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 311.7
            },
            {
                "time": 1563267600,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 66.84,
                "apparentTemperature": 66.91,
                "dewPoint": 59.86,
                "humidity": 0.78,
                "pressure": 1017.59,
                "windSpeed": 2.34,
                "windGust": 2.34,
                "windBearing": 355,
                "cloudCover": 0.02,
                "uvIndex": 0,
                "visibility": 9.957,
                "ozone": 313
            },
            {
                "time": 1563271200,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 66.87,
                "apparentTemperature": 66.91,
                "dewPoint": 59.69,
                "humidity": 0.78,
                "pressure": 1017.82,
                "windSpeed": 2.91,
                "windGust": 2.91,
                "windBearing": 0,
                "cloudCover": 0.02,
                "uvIndex": 0,
                "visibility": 9.863,
                "ozone": 315
            },
            {
                "time": 1563274800,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 68.83,
                "apparentTemperature": 69.07,
                "dewPoint": 61.67,
                "humidity": 0.78,
                "pressure": 1018.18,
                "windSpeed": 2.28,
                "windGust": 2.28,
                "windBearing": 14,
                "cloudCover": 0.06,
                "uvIndex": 0,
                "visibility": 9.654,
                "ozone": 317.3
            },
            {
                "time": 1563278400,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 72.46,
                "apparentTemperature": 72.81,
                "dewPoint": 63.02,
                "humidity": 0.72,
                "pressure": 1018.53,
                "windSpeed": 2.31,
                "windGust": 2.31,
                "windBearing": 73,
                "cloudCover": 0.07,
                "uvIndex": 1,
                "visibility": 9.188,
                "ozone": 320.3
            },
            {
                "time": 1563282000,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 77.14,
                "apparentTemperature": 77.53,
                "dewPoint": 63.66,
                "humidity": 0.63,
                "pressure": 1018.65,
                "windSpeed": 2.33,
                "windGust": 2.33,
                "windBearing": 127,
                "cloudCover": 0.01,
                "uvIndex": 3,
                "visibility": 8.154,
                "ozone": 318.3
            },
            {
                "time": 1563285600,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 77.28,
                "apparentTemperature": 77.51,
                "dewPoint": 62.1,
                "humidity": 0.6,
                "pressure": 1018.48,
                "windSpeed": 4.83,
                "windGust": 4.83,
                "windBearing": 184,
                "cloudCover": 0.01,
                "uvIndex": 5,
                "visibility": 7.449,
                "ozone": 314.6
            },
            {
                "time": 1563289200,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0.3,
                "temperature": 80.54,
                "apparentTemperature": 81.94,
                "dewPoint": 63.23,
                "humidity": 0.56,
                "pressure": 1018.15,
                "windSpeed": 4.58,
                "windGust": 4.58,
                "windBearing": 193,
                "cloudCover": 0.02,
                "uvIndex": 7,
                "visibility": 8.543,
                "ozone": 311.1
            },
            {
                "time": 1563292800,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 82.63,
                "apparentTemperature": 83.37,
                "dewPoint": 61.8,
                "humidity": 0.49,
                "pressure": 1017.81,
                "windSpeed": 4.54,
                "windGust": 4.54,
                "windBearing": 198,
                "cloudCover": 0.06,
                "uvIndex": 9,
                "visibility": 8.074,
                "ozone": 308.5
            },
            {
                "time": 1563296400,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 83.52,
                "apparentTemperature": 84.24,
                "dewPoint": 62.08,
                "humidity": 0.49,
                "pressure": 1017.31,
                "windSpeed": 5.87,
                "windGust": 5.87,
                "windBearing": 206,
                "cloudCover": 0.08,
                "uvIndex": 9,
                "visibility": 7.428,
                "ozone": 306
            },
            {
                "time": 1563300000,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 86.41,
                "apparentTemperature": 86.73,
                "dewPoint": 61.61,
                "humidity": 0.43,
                "pressure": 1016.79,
                "windSpeed": 7.48,
                "windGust": 7.48,
                "windBearing": 210,
                "cloudCover": 0.11,
                "uvIndex": 9,
                "visibility": 9.526,
                "ozone": 304.2
            },
            {
                "time": 1563303600,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 87.87,
                "apparentTemperature": 88.38,
                "dewPoint": 62.17,
                "humidity": 0.42,
                "pressure": 1016.21,
                "windSpeed": 8.1,
                "windGust": 8.1,
                "windBearing": 214,
                "cloudCover": 0.29,
                "uvIndex": 7,
                "visibility": 10,
                "ozone": 303.4
            },
            {
                "time": 1563307200,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 90.14,
                "apparentTemperature": 91.04,
                "dewPoint": 62.89,
                "humidity": 0.4,
                "pressure": 1015.66,
                "windSpeed": 9.04,
                "windGust": 11.89,
                "windBearing": 221,
                "cloudCover": 0.42,
                "uvIndex": 5,
                "visibility": 10,
                "ozone": 303.4
            },
            {
                "time": 1563310800,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 91.3,
                "apparentTemperature": 92.61,
                "dewPoint": 63.52,
                "humidity": 0.4,
                "pressure": 1015.23,
                "windSpeed": 9.74,
                "windGust": 15.74,
                "windBearing": 219,
                "cloudCover": 0.45,
                "uvIndex": 3,
                "visibility": 10,
                "ozone": 303.2
            },
            {
                "time": 1563314400,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 90.35,
                "apparentTemperature": 92.01,
                "dewPoint": 64.32,
                "humidity": 0.42,
                "pressure": 1015.06,
                "windSpeed": 9.81,
                "windGust": 16.69,
                "windBearing": 211,
                "cloudCover": 0.46,
                "uvIndex": 1,
                "visibility": 10,
                "ozone": 302.4
            },
            {
                "time": 1563318000,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 88.46,
                "apparentTemperature": 90.37,
                "dewPoint": 65.04,
                "humidity": 0.46,
                "pressure": 1015.02,
                "windSpeed": 10.22,
                "windGust": 17.09,
                "windBearing": 199,
                "cloudCover": 0.44,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 301.4
            },
            {
                "time": 1563321600,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 86.52,
                "apparentTemperature": 88.54,
                "dewPoint": 65.43,
                "humidity": 0.5,
                "pressure": 1015.07,
                "windSpeed": 9.97,
                "windGust": 17.23,
                "windBearing": 192,
                "cloudCover": 0.42,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 300.9
            },
            {
                "time": 1563325200,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 84.46,
                "apparentTemperature": 86.93,
                "dewPoint": 66.51,
                "humidity": 0.55,
                "pressure": 1015.28,
                "windSpeed": 9.33,
                "windGust": 16.48,
                "windBearing": 196,
                "cloudCover": 0.44,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 301.3
            },
            {
                "time": 1563328800,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.001,
                "precipProbability": 0.02,
                "precipType": "rain",
                "temperature": 80.54,
                "apparentTemperature": 83.02,
                "dewPoint": 67.32,
                "humidity": 0.64,
                "pressure": 1015.52,
                "windSpeed": 8.41,
                "windGust": 15.68,
                "windBearing": 202,
                "cloudCover": 0.34,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 302.2
            },
            {
                "time": 1563332400,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.002,
                "precipProbability": 0.02,
                "precipType": "rain",
                "temperature": 78.77,
                "apparentTemperature": 79.58,
                "dewPoint": 67.63,
                "humidity": 0.69,
                "pressure": 1015.59,
                "windSpeed": 7.18,
                "windGust": 14.32,
                "windBearing": 209,
                "cloudCover": 0.17,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 302.7
            }
        ]
    },
    "offset": -4
}

const hawaiiData = {
    "latitude": 22.217119,
    "longitude": -159.476044,
    "timezone": "Pacific/Honolulu",
    "hourly": {
        "summary": "Light rain until later this morning.",
        "icon": "rain",
        "data": [
            {
                "time": 1563271200,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.003,
                "precipProbability": 0.22,
                "precipType": "rain",
                "temperature": 77.03,
                "apparentTemperature": 77.99,
                "dewPoint": 68.78,
                "humidity": 0.76,
                "pressure": 1015.75,
                "windSpeed": 10.08,
                "windGust": 10.08,
                "windBearing": 94,
                "cloudCover": 0.91,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 284.5
            },
            {
                "time": 1563274800,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.003,
                "precipProbability": 0.26,
                "precipType": "rain",
                "temperature": 76.34,
                "apparentTemperature": 77.39,
                "dewPoint": 69.37,
                "humidity": 0.79,
                "pressure": 1015.24,
                "windSpeed": 6.57,
                "windGust": 8.42,
                "windBearing": 107,
                "cloudCover": 0.91,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 285.5
            },
            {
                "time": 1563278400,
                "summary": "Possible Drizzle",
                "icon": "rain",
                "precipIntensity": 0.005,
                "precipProbability": 0.49,
                "precipType": "rain",
                "temperature": 75.59,
                "apparentTemperature": 76.63,
                "dewPoint": 69.17,
                "humidity": 0.81,
                "pressure": 1014.98,
                "windSpeed": 10.35,
                "windGust": 10.35,
                "windBearing": 102,
                "cloudCover": 1,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 285.1
            },
            {
                "time": 1563282000,
                "summary": "Possible Drizzle",
                "icon": "rain",
                "precipIntensity": 0.005,
                "precipProbability": 0.44,
                "precipType": "rain",
                "temperature": 75.91,
                "apparentTemperature": 77.06,
                "dewPoint": 70.01,
                "humidity": 0.82,
                "pressure": 1014.64,
                "windSpeed": 9.35,
                "windGust": 9.35,
                "windBearing": 89,
                "cloudCover": 0.75,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 285.2
            },
            {
                "time": 1563285600,
                "summary": "Drizzle",
                "icon": "rain",
                "precipIntensity": 0.014,
                "precipProbability": 0.75,
                "precipType": "rain",
                "temperature": 75.87,
                "apparentTemperature": 76.86,
                "dewPoint": 68.82,
                "humidity": 0.79,
                "pressure": 1014.74,
                "windSpeed": 8.78,
                "windGust": 8.78,
                "windBearing": 94,
                "cloudCover": 0.91,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 285.5
            },
            {
                "time": 1563289200,
                "summary": "Light Rain",
                "icon": "rain",
                "precipIntensity": 0.028,
                "precipProbability": 0.9,
                "precipType": "rain",
                "temperature": 74.01,
                "apparentTemperature": 75.15,
                "dewPoint": 69.56,
                "humidity": 0.86,
                "pressure": 1015.06,
                "windSpeed": 7.31,
                "windGust": 8.13,
                "windBearing": 110,
                "cloudCover": 1,
                "uvIndex": 0,
                "visibility": 7.963,
                "ozone": 286
            },
            {
                "time": 1563292800,
                "summary": "Light Rain",
                "icon": "rain",
                "precipIntensity": 0.025,
                "precipProbability": 0.85,
                "precipType": "rain",
                "temperature": 74.78,
                "apparentTemperature": 75.85,
                "dewPoint": 69.17,
                "humidity": 0.83,
                "pressure": 1015.01,
                "windSpeed": 8.13,
                "windGust": 8.13,
                "windBearing": 93,
                "cloudCover": 1,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 287
            },
            {
                "time": 1563296400,
                "summary": "Possible Drizzle",
                "icon": "rain",
                "precipIntensity": 0.01,
                "precipProbability": 0.44,
                "precipType": "rain",
                "temperature": 75.08,
                "apparentTemperature": 75.98,
                "dewPoint": 67.97,
                "humidity": 0.79,
                "pressure": 1015.79,
                "windSpeed": 7.96,
                "windGust": 9.72,
                "windBearing": 81,
                "cloudCover": 0.91,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 288.4
            },
            {
                "time": 1563300000,
                "summary": "Possible Drizzle",
                "icon": "rain",
                "precipIntensity": 0.009,
                "precipProbability": 0.42,
                "precipType": "rain",
                "temperature": 75.76,
                "apparentTemperature": 76.72,
                "dewPoint": 68.54,
                "humidity": 0.78,
                "pressure": 1016.08,
                "windSpeed": 8.61,
                "windGust": 10.28,
                "windBearing": 77,
                "cloudCover": 0.91,
                "uvIndex": 1,
                "visibility": 10,
                "ozone": 289.8
            },
            {
                "time": 1563303600,
                "summary": "Possible Drizzle",
                "icon": "rain",
                "precipIntensity": 0.007,
                "precipProbability": 0.37,
                "precipType": "rain",
                "temperature": 77.36,
                "apparentTemperature": 78.22,
                "dewPoint": 67.95,
                "humidity": 0.73,
                "pressure": 1016.3,
                "windSpeed": 9.54,
                "windGust": 10.93,
                "windBearing": 81,
                "cloudCover": 0.81,
                "uvIndex": 3,
                "visibility": 10,
                "ozone": 291.4
            },
            {
                "time": 1563307200,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.003,
                "precipProbability": 0.16,
                "precipType": "rain",
                "temperature": 79.91,
                "apparentTemperature": 82.78,
                "dewPoint": 69.14,
                "humidity": 0.7,
                "pressure": 1016.18,
                "windSpeed": 12.64,
                "windGust": 14.25,
                "windBearing": 88,
                "cloudCover": 0.48,
                "uvIndex": 5,
                "visibility": 10,
                "ozone": 293
            },
            {
                "time": 1563310800,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 82.28,
                "apparentTemperature": 86.37,
                "dewPoint": 70.38,
                "humidity": 0.67,
                "pressure": 1015.93,
                "windSpeed": 15.15,
                "windGust": 16.29,
                "windBearing": 88,
                "cloudCover": 0.26,
                "uvIndex": 8,
                "visibility": 10,
                "ozone": 294.2
            },
            {
                "time": 1563314400,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.001,
                "precipProbability": 0.02,
                "precipType": "rain",
                "temperature": 82.86,
                "apparentTemperature": 87.02,
                "dewPoint": 70.21,
                "humidity": 0.66,
                "pressure": 1015.75,
                "windSpeed": 14.44,
                "windGust": 16,
                "windBearing": 87,
                "cloudCover": 0.25,
                "uvIndex": 10,
                "visibility": 10,
                "ozone": 294.7
            },
            {
                "time": 1563318000,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.002,
                "precipProbability": 0.02,
                "precipType": "rain",
                "temperature": 83.32,
                "apparentTemperature": 87.83,
                "dewPoint": 70.61,
                "humidity": 0.66,
                "pressure": 1015.44,
                "windSpeed": 14.18,
                "windGust": 15.73,
                "windBearing": 85,
                "cloudCover": 0.25,
                "uvIndex": 10,
                "visibility": 10,
                "ozone": 294.9
            },
            {
                "time": 1563321600,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.003,
                "precipProbability": 0.03,
                "precipType": "rain",
                "temperature": 83.84,
                "apparentTemperature": 88.94,
                "dewPoint": 71.29,
                "humidity": 0.66,
                "pressure": 1015.05,
                "windSpeed": 14.24,
                "windGust": 15.63,
                "windBearing": 83,
                "cloudCover": 0.29,
                "uvIndex": 9,
                "visibility": 10,
                "ozone": 295.1
            },
            {
                "time": 1563325200,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.006,
                "precipProbability": 0.06,
                "precipType": "rain",
                "temperature": 83.34,
                "apparentTemperature": 88.42,
                "dewPoint": 71.52,
                "humidity": 0.68,
                "pressure": 1014.66,
                "windSpeed": 13.99,
                "windGust": 15.85,
                "windBearing": 84,
                "cloudCover": 0.41,
                "uvIndex": 6,
                "visibility": 10,
                "ozone": 295.6
            },
            {
                "time": 1563328800,
                "summary": "Humid and Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.013,
                "precipProbability": 0.13,
                "precipType": "rain",
                "temperature": 82.13,
                "apparentTemperature": 87.06,
                "dewPoint": 72.06,
                "humidity": 0.72,
                "pressure": 1014.19,
                "windSpeed": 14.04,
                "windGust": 16.26,
                "windBearing": 83,
                "cloudCover": 0.56,
                "uvIndex": 4,
                "visibility": 10,
                "ozone": 296.2
            },
            {
                "time": 1563332400,
                "summary": "Humid and Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.021,
                "precipProbability": 0.2,
                "precipType": "rain",
                "temperature": 81.16,
                "apparentTemperature": 85.85,
                "dewPoint": 72.56,
                "humidity": 0.75,
                "pressure": 1014.01,
                "windSpeed": 14.81,
                "windGust": 16.58,
                "windBearing": 84,
                "cloudCover": 0.63,
                "uvIndex": 2,
                "visibility": 10,
                "ozone": 297
            },
            {
                "time": 1563336000,
                "summary": "Humid and Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.013,
                "precipProbability": 0.17,
                "precipType": "rain",
                "temperature": 80.42,
                "apparentTemperature": 84.57,
                "dewPoint": 72.28,
                "humidity": 0.76,
                "pressure": 1014.29,
                "windSpeed": 14.18,
                "windGust": 16.66,
                "windBearing": 87,
                "cloudCover": 0.53,
                "uvIndex": 1,
                "visibility": 10,
                "ozone": 297.8
            },
            {
                "time": 1563339600,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.01,
                "precipProbability": 0.13,
                "precipType": "rain",
                "temperature": 79.5,
                "apparentTemperature": 82.97,
                "dewPoint": 72,
                "humidity": 0.78,
                "pressure": 1014.86,
                "windSpeed": 14.3,
                "windGust": 16.64,
                "windBearing": 91,
                "cloudCover": 0.36,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 298.7
            },
            {
                "time": 1563343200,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.006,
                "precipProbability": 0.09,
                "precipType": "rain",
                "temperature": 78.49,
                "apparentTemperature": 79.81,
                "dewPoint": 71.91,
                "humidity": 0.8,
                "pressure": 1015.26,
                "windSpeed": 14.49,
                "windGust": 16.98,
                "windBearing": 92,
                "cloudCover": 0.27,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 299.4
            },
            {
                "time": 1563346800,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.01,
                "precipProbability": 0.12,
                "precipType": "rain",
                "temperature": 77.56,
                "apparentTemperature": 78.91,
                "dewPoint": 71.89,
                "humidity": 0.83,
                "pressure": 1015.79,
                "windSpeed": 14.72,
                "windGust": 18.18,
                "windBearing": 95,
                "cloudCover": 0.37,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 299.6
            },
            {
                "time": 1563350400,
                "summary": "Humid and Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.011,
                "precipProbability": 0.13,
                "precipType": "rain",
                "temperature": 77.18,
                "apparentTemperature": 78.56,
                "dewPoint": 72.07,
                "humidity": 0.84,
                "pressure": 1016.17,
                "windSpeed": 15.02,
                "windGust": 19.73,
                "windBearing": 97,
                "cloudCover": 0.55,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 299.6
            },
            {
                "time": 1563354000,
                "summary": "Humid and Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.016,
                "precipProbability": 0.18,
                "precipType": "rain",
                "temperature": 76.93,
                "apparentTemperature": 78.32,
                "dewPoint": 72.1,
                "humidity": 0.85,
                "pressure": 1016.3,
                "windSpeed": 15.05,
                "windGust": 20.57,
                "windBearing": 99,
                "cloudCover": 0.69,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 299.2
            }
        ]
    },
    "offset": -10
}